language: php

sudo: false

php:
  - 7.4

matrix:
  include:
    - php: 7.4
    - php: 7.4
      env: dependencies=lowest

install:
  - composer self-update

before_script:
  - phpenv config-add mongodb.ini
  - make

script:
    - make qa
    - make test
